import {StyleSheet, Dimensions, StatusBar} from 'react-native';

export default StyleSheet.create({
  contianer: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: StatusBar.currentHeight,
  },
  q_container: {
    width: Dimensions.get('window').width / 1.03,
    borderRadius: 30,
    padding: 20,
    backgroundColor: '#e3e3e3',
    justifyContent: 'center',
  },
  q_container_space: {
    height: Dimensions.get('window').height / 3,
    justifyContent: 'center',
  },
  q_text: {
    color: 'black',
    fontSize: Dimensions.get('window').width / 25,
    fontWeight: '400',
    marginBottom: 20,
  },
  q_text_null: {
    fontSize: 0,
  },
  q_text_alt: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: Dimensions.get('window').width / 22,
    justifyContent: 'flex-end',
  },

  button_a: {
    borderWidth: 2,
    borderColor: 'mediumblue',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_a_text: {
    color: 'black',
    fontWeight: '600',
    fontSize: 15,
    padding: 2,
    paddingHorizontal: 15,
  },
  button_b: {
    borderWidth: 2,
    borderColor: 'mediumblue',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_b_text: {
    color: 'black',
    fontWeight: '600',
    fontSize: 15,
    padding: 2,
    paddingHorizontal: 15,
  },
  button_c: {
    borderWidth: 2,
    borderColor: 'mediumblue',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_c_text: {
    color: 'black',
    fontWeight: '600',
    fontSize: 15,
    padding: 2,
    paddingHorizontal: 15,
  },
  button_d: {
    borderWidth: 2,
    borderColor: 'mediumblue',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_true: {
    borderWidth: 2,
    borderColor: '#008C30',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_false: {
    borderWidth: 2,
    borderColor: 'red',
    borderRadius: Dimensions.get('window').width / 18,
    width: Dimensions.get('window').width / 1.15,
    height: Dimensions.get('window').height / 13,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  button_d_text: {
    color: 'black',
    fontWeight: '600',
    fontSize: 15,
    padding: 2,
    paddingHorizontal: 15,
  },
  button_container: {
    justifyContent: 'space-evenly',
    height: Dimensions.get('window').height / 2.3,
  },
  next_button: {
    backgroundColor: 'mediumblue',
    borderRadius: Dimensions.get('window').width,
    justifyContent: 'center',
    alignItems: 'center',
    width: Dimensions.get('window').width / 2.3,
    height: Dimensions.get('window').height / 13,
    marginBottom: Dimensions.get('window').height / 80,
  },
  next_button_text: {
    color: 'white',
    fontWeight: '600',
    fontSize: Dimensions.get('window').width / 10.5,
  },
  remaining_question_text: {
    color: 'white',
    fontWeight: '500',
    fontSize: 20,
    marginLeft: 3,
  },
  remaining_question_number: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 20,
  },
  true: {
    color: 'white',
    fontWeight: '500',
    fontSize: 20,
    marginRight: 3,
  },
  true_counter: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 20,
  },
  wrong: {
    color: 'white',
    fontWeight: '500',
    fontSize: 20,
    marginRight: 3,
  },
  wrong_counter: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 20,
  },
  true_container: {
    backgroundColor: '#008C30',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: 30,
    width: 100,
    height: 37,
  },
  wrong_container: {
    backgroundColor: '#C80000',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginLeft: 6,
    borderRadius: 30,
    width: 100,
    height: 37,
  },
  true_counter_bg: {
    backgroundColor: 'white',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrong_counter_bg: {
    backgroundColor: 'white',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  remaining_question_container: {
    backgroundColor: '#FF9900',
    width: 100,
    height: 37,
    borderRadius: 27,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginLeft: 35,
  },
  remaining_question_counter_bg: {
    backgroundColor: 'white',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header_container: {
    backgroundColor: 'black',
    width: Dimensions.get('window').width / 1.3,
    height: Dimensions.get('window').height / 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Dimensions.get('window').width,
    marginTop: 5,
  },
  header_text: {
    color: 'white',
    fontSize: Dimensions.get('window').width / 15,
    fontWeight: 'bold',
  },
});
